export const duelMapTilesData = [
  {
    id: 0,
    positionX: -4.545,
    positionZ: -4.45,
    rotationY: 240,
    tileName: 'grass',
  },
  {
    id: 1,
    positionX: -3.535,
    positionZ: -4.45,
    rotationY: 240,
    tileName: 'sand-rocks',
  },
  {
    id: 2,
    positionX: -2.525,
    positionZ: -4.45,
    rotationY: 0,
    tileName: 'sand-desert',
  },
  {
    id: 3,
    positionX: -1.515,
    positionZ: -4.45,
    rotationY: 300,
    tileName: 'grass',
  },
  {
    id: 4,
    positionX: -0.505,
    positionZ: -4.45,
    rotationY: 120,
    tileName: 'grass-hill',
  },
  {
    id: 5,
    positionX: 0.505,
    positionZ: -4.45,
    rotationY: 60,
    tileName: 'sand-rocks',
  },
  {
    id: 6,
    positionX: 1.515,
    positionZ: -4.45,
    rotationY: 240,
    tileName: 'grass-forest',
  },
  {
    id: 7,
    positionX: 2.525,
    positionZ: -4.45,
    rotationY: 300,
    tileName: 'grass-hill',
  },
  {
    id: 8,
    positionX: 3.535,
    positionZ: -4.45,
    rotationY: 180,
    tileName: 'grass-hill',
  },
  {
    id: 9,
    positionX: 4.545,
    positionZ: -4.45,
    rotationY: 60,
    tileName: 'sand-desert',
  },
  {
    id: 10,
    positionX: -4.04,
    positionZ: -3.56,
    rotationY: 60,
    tileName: 'stone-rocks',
  },
  {
    id: 11,
    positionX: -3.03,
    positionZ: -3.56,
    rotationY: 300,
    tileName: 'stone-mountain',
  },
  {
    id: 12,
    positionX: -2.02,
    positionZ: -3.56,
    rotationY: 300,
    tileName: 'sand-rocks',
  },
  {
    id: 13,
    positionX: -1.01,
    positionZ: -3.56,
    rotationY: 0,
    tileName: 'sand-desert',
  },
  {
    id: 14,
    positionX: 0,
    positionZ: -3.56,
    rotationY: 180,
    tileName: 'sand-rocks',
  },
  {
    id: 15,
    positionX: 1.01,
    positionZ: -3.56,
    rotationY: 240,
    tileName: 'sand-rocks',
  },
  {
    id: 16,
    positionX: 2.02,
    positionZ: -3.56,
    rotationY: 180,
    tileName: 'grass-forest',
  },
  {
    id: 17,
    positionX: 3.03,
    positionZ: -3.56,
    rotationY: 120,
    tileName: 'grass-forest',
  },
  {
    id: 18,
    positionX: 4.04,
    positionZ: -3.56,
    rotationY: 60,
    tileName: 'stone-rocks',
  },
  {
    id: 19,
    positionX: -4.545,
    positionZ: -2.67,
    rotationY: 300,
    tileName: 'dirt-lumber',
  },
  {
    id: 20,
    positionX: -3.535,
    positionZ: -2.67,
    rotationY: 300,
    tileName: 'dirt',
  },
  {
    id: 21,
    positionX: -2.525,
    positionZ: -2.67,
    rotationY: 300,
    tileName: 'dirt-lumber',
  },
  {
    id: 22,
    positionX: -1.515,
    positionZ: -2.67,
    rotationY: 60,
    tileName: 'dirt-lumber',
  },
  {
    id: 23,
    positionX: -0.505,
    positionZ: -2.67,
    rotationY: 120,
    tileName: 'stone-rocks',
  },
  {
    id: 24,
    positionX: 0.505,
    positionZ: -2.67,
    rotationY: 120,
    tileName: 'stone-hill',
  },
  {
    id: 25,
    positionX: 1.515,
    positionZ: -2.67,
    rotationY: 60,
    tileName: 'dirt-lumber',
  },
  {
    id: 26,
    positionX: 2.525,
    positionZ: -2.67,
    rotationY: 120,
    tileName: 'stone',
  },
  {
    id: 27,
    positionX: 3.535,
    positionZ: -2.67,
    rotationY: 240,
    tileName: 'stone-rocks',
  },
  {
    id: 28,
    positionX: 4.545,
    positionZ: -2.67,
    rotationY: 0,
    tileName: 'stone-mountain',
  },
  {
    id: 29,
    positionX: -4.04,
    positionZ: -1.78,
    rotationY: 240,
    tileName: 'stone-hill',
  },
  {
    id: 30,
    positionX: -3.03,
    positionZ: -1.78,
    rotationY: 60,
    tileName: 'dirt-lumber',
  },
  {
    id: 31,
    positionX: -2.02,
    positionZ: -1.78,
    rotationY: 300,
    tileName: 'grass-forest',
  },
  {
    id: 32,
    positionX: -1.01,
    positionZ: -1.78,
    rotationY: 180,
    tileName: 'sand',
  },
  {
    id: 33,
    positionX: 0,
    positionZ: -1.78,
    rotationY: 120,
    tileName: 'stone-hill',
  },
  {
    id: 34,
    positionX: 1.01,
    positionZ: -1.78,
    rotationY: 300,
    tileName: 'sand-desert',
  },
  {
    id: 35,
    positionX: 2.02,
    positionZ: -1.78,
    rotationY: 60,
    tileName: 'stone-mountain',
  },
  {
    id: 36,
    positionX: 3.03,
    positionZ: -1.78,
    rotationY: 120,
    tileName: 'stone-hill',
  },
  {
    id: 37,
    positionX: 4.04,
    positionZ: -1.78,
    rotationY: 120,
    tileName: 'sand',
  },
  {
    id: 38,
    positionX: -4.545,
    positionZ: -0.89,
    rotationY: 60,
    tileName: 'stone-hill',
  },
  {
    id: 39,
    positionX: -3.535,
    positionZ: -0.89,
    rotationY: 60,
    tileName: 'dirt',
  },
  {
    id: 40,
    positionX: -2.525,
    positionZ: -0.89,
    rotationY: 180,
    tileName: 'grass',
  },
  {
    id: 41,
    positionX: -1.515,
    positionZ: -0.89,
    rotationY: 300,
    tileName: 'sand',
  },
  {
    id: 42,
    positionX: -0.505,
    positionZ: -0.89,
    rotationY: 180,
    tileName: 'dirt',
  },
  {
    id: 43,
    positionX: 0.505,
    positionZ: -0.89,
    rotationY: 240,
    tileName: 'stone-rocks',
  },
  {
    id: 44,
    positionX: 1.515,
    positionZ: -0.89,
    rotationY: 120,
    tileName: 'grass-forest',
  },
  {
    id: 45,
    positionX: 2.525,
    positionZ: -0.89,
    rotationY: 300,
    tileName: 'stone-hill',
  },
  {
    id: 46,
    positionX: 3.535,
    positionZ: -0.89,
    rotationY: 180,
    tileName: 'stone-mountain',
  },
  {
    id: 47,
    positionX: 4.545,
    positionZ: -0.89,
    rotationY: 300,
    tileName: 'sand',
  },
  {
    id: 48,
    positionX: -4.04,
    positionZ: 0,
    rotationY: 120,
    tileName: 'dirt-lumber',
  },
  {
    id: 49,
    positionX: -3.03,
    positionZ: 0,
    rotationY: 120,
    tileName: 'stone',
  },
  {
    id: 50,
    positionX: -2.02,
    positionZ: 0,
    rotationY: 180,
    tileName: 'sand-rocks',
  },
  {
    id: 51,
    positionX: -1.01,
    positionZ: 0,
    rotationY: 300,
    tileName: 'stone-rocks',
  },
  {
    id: 52,
    positionX: 0,
    positionZ: 0,
    rotationY: 240,
    tileName: 'sand-desert',
  },
  {
    id: 53,
    positionX: 1.01,
    positionZ: 0,
    rotationY: 60,
    tileName: 'grass-hill',
  },
  {
    id: 54,
    positionX: 2.02,
    positionZ: 0,
    rotationY: 60,
    tileName: 'stone-mountain',
  },
  {
    id: 55,
    positionX: 3.03,
    positionZ: 0,
    rotationY: 240,
    tileName: 'grass-hill',
  },
  {
    id: 56,
    positionX: 4.04,
    positionZ: 0,
    rotationY: 60,
    tileName: 'stone',
  },
  {
    id: 57,
    positionX: -4.545,
    positionZ: 0.89,
    rotationY: 240,
    tileName: 'grass-forest',
  },
  {
    id: 58,
    positionX: -3.535,
    positionZ: 0.89,
    rotationY: 180,
    tileName: 'sand-desert',
  },
  {
    id: 59,
    positionX: -2.525,
    positionZ: 0.89,
    rotationY: 240,
    tileName: 'dirt-lumber',
  },
  {
    id: 60,
    positionX: -1.515,
    positionZ: 0.89,
    rotationY: 180,
    tileName: 'sand-desert',
  },
  {
    id: 61,
    positionX: -0.505,
    positionZ: 0.89,
    rotationY: 240,
    tileName: 'stone-mountain',
  },
  {
    id: 62,
    positionX: 0.505,
    positionZ: 0.89,
    rotationY: 60,
    tileName: 'grass-forest',
  },
  {
    id: 63,
    positionX: 1.515,
    positionZ: 0.89,
    rotationY: 180,
    tileName: 'dirt-lumber',
  },
  {
    id: 64,
    positionX: 2.525,
    positionZ: 0.89,
    rotationY: 180,
    tileName: 'dirt-lumber',
  },
  {
    id: 65,
    positionX: 3.535,
    positionZ: 0.89,
    rotationY: 180,
    tileName: 'sand',
  },
  {
    id: 66,
    positionX: 4.545,
    positionZ: 0.89,
    rotationY: 60,
    tileName: 'dirt',
  },
  {
    id: 67,
    positionX: -4.04,
    positionZ: 1.78,
    rotationY: 240,
    tileName: 'grass-hill',
  },
  {
    id: 68,
    positionX: -3.03,
    positionZ: 1.78,
    rotationY: 300,
    tileName: 'grass-forest',
  },
  {
    id: 69,
    positionX: -2.02,
    positionZ: 1.78,
    rotationY: 0,
    tileName: 'dirt-lumber',
  },
  {
    id: 70,
    positionX: -1.01,
    positionZ: 1.78,
    rotationY: 240,
    tileName: 'stone-rocks',
  },
  {
    id: 71,
    positionX: 0,
    positionZ: 1.78,
    rotationY: 120,
    tileName: 'grass',
  },
  {
    id: 72,
    positionX: 1.01,
    positionZ: 1.78,
    rotationY: 120,
    tileName: 'stone',
  },
  {
    id: 73,
    positionX: 2.02,
    positionZ: 1.78,
    rotationY: 60,
    tileName: 'stone-mountain',
  },
  {
    id: 74,
    positionX: 3.03,
    positionZ: 1.78,
    rotationY: 120,
    tileName: 'stone-mountain',
  },
  {
    id: 75,
    positionX: 4.04,
    positionZ: 1.78,
    rotationY: 120,
    tileName: 'sand-rocks',
  },
  {
    id: 76,
    positionX: -4.545,
    positionZ: 2.67,
    rotationY: 300,
    tileName: 'stone-hill',
  },
  {
    id: 77,
    positionX: -3.535,
    positionZ: 2.67,
    rotationY: 0,
    tileName: 'dirt-lumber',
  },
  {
    id: 78,
    positionX: -2.525,
    positionZ: 2.67,
    rotationY: 120,
    tileName: 'stone-hill',
  },
  {
    id: 79,
    positionX: -1.515,
    positionZ: 2.67,
    rotationY: 180,
    tileName: 'sand-desert',
  },
  {
    id: 80,
    positionX: -0.505,
    positionZ: 2.67,
    rotationY: 240,
    tileName: 'sand',
  },
  {
    id: 81,
    positionX: 0.505,
    positionZ: 2.67,
    rotationY: 120,
    tileName: 'stone-hill',
  },
  {
    id: 82,
    positionX: 1.515,
    positionZ: 2.67,
    rotationY: 120,
    tileName: 'dirt',
  },
  {
    id: 83,
    positionX: 2.525,
    positionZ: 2.67,
    rotationY: 60,
    tileName: 'sand-rocks',
  },
  {
    id: 84,
    positionX: 3.535,
    positionZ: 2.67,
    rotationY: 60,
    tileName: 'stone',
  },
  {
    id: 85,
    positionX: 4.545,
    positionZ: 2.67,
    rotationY: 180,
    tileName: 'dirt-lumber',
  },
  {
    id: 86,
    positionX: -4.04,
    positionZ: 3.56,
    rotationY: 240,
    tileName: 'stone-mountain',
  },
  {
    id: 87,
    positionX: -3.03,
    positionZ: 3.56,
    rotationY: 120,
    tileName: 'grass',
  },
  {
    id: 88,
    positionX: -2.02,
    positionZ: 3.56,
    rotationY: 300,
    tileName: 'sand-rocks',
  },
  {
    id: 89,
    positionX: -1.01,
    positionZ: 3.56,
    rotationY: 180,
    tileName: 'stone-hill',
  },
  {
    id: 90,
    positionX: 0,
    positionZ: 3.56,
    rotationY: 180,
    tileName: 'dirt-lumber',
  },
  {
    id: 91,
    positionX: 1.01,
    positionZ: 3.56,
    rotationY: 240,
    tileName: 'dirt-lumber',
  },
  {
    id: 92,
    positionX: 2.02,
    positionZ: 3.56,
    rotationY: 120,
    tileName: 'grass-hill',
  },
  {
    id: 93,
    positionX: 3.03,
    positionZ: 3.56,
    rotationY: 240,
    tileName: 'stone',
  },
  {
    id: 94,
    positionX: 4.04,
    positionZ: 3.56,
    rotationY: 0,
    tileName: 'grass-hill',
  },
  {
    id: 95,
    positionX: -4.545,
    positionZ: 4.45,
    rotationY: 240,
    tileName: 'stone-mountain',
  },
  {
    id: 96,
    positionX: -3.535,
    positionZ: 4.45,
    rotationY: 180,
    tileName: 'grass-hill',
  },
  {
    id: 97,
    positionX: -2.525,
    positionZ: 4.45,
    rotationY: 60,
    tileName: 'stone-hill',
  },
  {
    id: 98,
    positionX: -1.515,
    positionZ: 4.45,
    rotationY: 60,
    tileName: 'stone-mountain',
  },
  {
    id: 99,
    positionX: -0.505,
    positionZ: 4.45,
    rotationY: 60,
    tileName: 'stone-hill',
  },
  {
    id: 100,
    positionX: 0.505,
    positionZ: 4.45,
    rotationY: 180,
    tileName: 'sand-desert',
  },
  {
    id: 101,
    positionX: 1.515,
    positionZ: 4.45,
    rotationY: 60,
    tileName: 'dirt-lumber',
  },
  {
    id: 102,
    positionX: 2.525,
    positionZ: 4.45,
    rotationY: 0,
    tileName: 'stone',
  },
  {
    id: 103,
    positionX: 3.535,
    positionZ: 4.45,
    rotationY: 0,
    tileName: 'stone',
  },
  {
    id: 104,
    positionX: 4.545,
    positionZ: 4.45,
    rotationY: 120,
    tileName: 'dirt',
  },
];
